
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workloads-alexeldeib-xyz-v1-demo
  failurePolicy: Fail
  name: mdemo.kb.io
  rules:
  - apiGroups:
    - workloads.alexeldeib.xyz
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - demoes

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-workloads-alexeldeib-xyz-v1-demo
  failurePolicy: Fail
  name: vdemo.kb.io
  rules:
  - apiGroups:
    - workloads.alexeldeib.xyz
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - demoes
